### ISSUE TITLE
Game exits as soon as I press "i" to leave instructions page on MacOS

### ISSUE THREAD

**Issue by 9Katastrophes** [azhang999/crime-cat#25]
How to reproduce:
1. Start up the game
2. Press "i" on the menu screen
3. Observe how the game exits without producing some kind of error message in the terminal or Apple error report.

**Comment by emmaloool** [comment]
Usually there should be an Apple error report. Can you try again?

**Comment by azhang999** [comment]
Fixed sound segfault bug, thanks for play testing and finding this bug!
