### ISSUE TITLE
Game crashes quickly on windows

### ISSUE THREAD

**Issue by mwmccoy** [azhang999/crime-cat#26]
I am able to make it through the menu screens consistently, but crash quickly upon entering the real game. It sometimes crashes immediately after pressing i with no other inputs, and sometimes makes it a small ways before crashing. Spamming the mouse buttons seems to increase the chances of it happening, but I might just be fooling myself. The first run of the game was much more stable, and I was able to play for around 20 seconds before a crash. Waiting for a few seconds on the instructions screen seems to help as well.

**Comment by annehe9** [comment]
Bump, the game crashes past the instructions screen. The game will open, but sometimes I won't be able to move or input anything, and sometimes I can move a few steps before it crashes. I also noticed that spamming inputs made it crash faster, and waiting a few seconds allowed me to progress slightly further in the game. I am also on Windows. Leaving the instruction screen open for longer did not help this issue for me.

**Comment by azhang999** [comment]
Fixed sound segfault bug and an iterator bug, thanks for play testing and finding this bug!
